# Generated by Django 4.1.2 on 2022-10-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_doctor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='title',
            field=models.CharField(choices=[('Dr.', 'Dr.'), ('Prof.Dr.', 'Prof.Dr.'), ('Dr.rer.nat.', 'Dr.rer.nat.')], default='Dr.', max_length=20),
        ),
    ]
