# Generated by Django 4.1.2 on 2022-10-16 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_doctor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Dr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portal.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portal.patient'),
        ),
    ]
