# Generated by Django 4.1.2 on 2022-10-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_appointment_dr_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Allgemeinmedizin', 'Allgemeinmedizin'), ('Radiologe', 'Radiologe'), ('Hautarzt', 'Hautarzt'), ('Augenarzt', 'Augenarzt')], default='Allgemeinmedizin', max_length=20),
        ),
    ]
