# Generated by Django 4.1.2 on 2022-10-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_appointment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Dr',
            new_name='dr',
        ),
    ]
