# Generated by Django 4.1.2 on 2022-10-23 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_rename_dr_appointment_dr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
